# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/android:api-28-alpha
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: gradle dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      # run tests!
      - run: 
          name: gradle test
          command: ./gradlew test

      # run build
      - run: 
          name: gradle build
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./gradlew assembleRelease
            else
              ./gradlew assembleDebug
            fi

      - store_artifacts:
          path: ./app/build/outputs
          destination: build

      - deploy:
          command: |
          if [ "${CIRCLE_BRANCH}" == "develop" -o "${CIRCLE_BRANCH}" == "master" ]; then
            curl -F "token=${DEPLOY_GATE_KEY}" -F "file=@app/build/outputs/apk/debug/app-debug.apk" -F "message=deployed" https://deploygate.com/api/users/kappa-lab/apps
          fi


